### PR TITLE
Bundling with correct type defs

### PR DESCRIPTION
**Pull request by chandru89new**

### CODE REVIEW

**Comment by chandru89new** [comment]
Current dependencies on/for this PR:
* main
  * **PR #37** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/37" target="_blank">Graphite</a>  👈
    * **PR #42** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/42" target="_blank">Graphite</a> 
      * **PR #43** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/43" target="_blank">Graphite</a> 
    * **PR #38** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/38" target="_blank">Graphite</a> 
    * **PR #33** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/33" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/37?utm_source=stack-comment).

**Comment by chandru89new** [comment]
Current dependencies on/for this PR:
* main
  * **PR #31** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/31" target="_blank">Graphite</a> 
    * **PR #35** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/35" target="_blank">Graphite</a> 
    * **PR #32** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/32" target="_blank">Graphite</a> 
    * **PR #33** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/33" target="_blank">Graphite</a> 
      * **PR #37** <a href="https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/37" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/afsheen-01/vercel-ts-sdk/37?utm_source=stack-comment).

**Comment by chandru89new** [comment]
Link #34

**Comment by chandru89new** [comment]
@afsheen-01 you can check this PR and merge it if you're okay with it. 

This is not a full-fledged solution. What it does currently is this:

- uses `parcel` to build a bundled `js` file from the source. But does not build the `.d.ts` files because I removed the `types` entry from `package.json`
- uses `tsc` to build just the `.d.ts` files from the source and put into the same `dist` folder as `parcel`. Luckily neither `tsc` nor `parcel` clean the directory before putting files into it so they both can run sequentially.

What this ultimately does is create a dist folder with `index.js` compiled by `parcel`, and a bunch of `.d.ts` files compiled by `tsc`.

Net result is that type defs work just as intended, no more issue #34 .

I will keep the issue open/modified, however, just so we try and find a better solution for this at some point. 

I'll add more details in the original issue.

**Review by afsheen-01 — APPROVED** [review]

**Pull request merged**
